// imports/components/formBuilder/fields/itemList.svelte
<script>
    /**
     * Draggable item list.
     *
     * @memberof Components:Form
     * @function itemList
     * @locus Client
     * @augments fieldWrapper
     *
     * @param {Object} field
     *
     * @emits 'on-inputentry' {value: value, error: errorVal} with text, number or other types
     *
     */

    //* common props from parent
    export let field = {};

    //* support functions
    import Icon from '/imports/components/elements/icon.svelte'
    import Sortable from '/imports/components/elements/rowDragDrop.svelte'
    import {getContext, createEventDispatcher} from 'svelte';
    const dispatch = createEventDispatcher();

    //* local reactive variable
    let list = [];
    let key = field.params.key;
    let uniqueId = Math.random();

    $: setValue(field.value);

    //* functions that mutate local variables
    function setValue(val){
        list = val;
    }

    function updateList(newList){
        let updated = newList.map( (nl, idx) =>  {
            nl.id = idx + 1;
            return nl;
        });

        list = updated;
        dispatch('on-inputentry', {value: list, error: false});
    }

    //* event handlers
    function addRow(){
        let newList = list;
        let addItem = {
            id: list.length + 1,
            check: "",
            text: "",
        };

        newList.push(addItem);
        updateList(newList)
    }

    function deleteRow(rowid) {
        let newList = list;
        newList = newList.filter(row => row.id !== rowid);
        updateList(newList)
    }

    function updateElement(item, prop, value) {
        item[prop] = value;
        updateList(list);
    }

    function sortList(ev){
        let newList = ev.detail;
        updateList(newList)
    }

</script>




<div class="box">

    <button class="button btn-rounded is-primary mb-3" on:click="{addRow}">
        <Icon icon='{getContext("iconRowAdd")}' class="text-1dot5rem"/>
    </button>

    <Sortable
        bind:list={list}
        key={field.params.key}
        on:sort={sortList}
        let:item={item}>

        <div class="level mb-2">
            <div class="w-10">
                <span class="row-id">{item.id}</span>
            </div>

            {#if field.params.showCheck}
                <div class="mr-3" style="height: 1.5rem; width: 1.5rem;">
                    <input type="checkbox"
                           class="is-checkradio is-info has-background-color"
                           title=""
                           id="{'checkbox_' + uniqueId + '_' + item.id}"
                           checked="{item.check}"
                           on:change="{e => updateElement(item, 'check', e.target.checked)}">

                    <label for="{'checkbox_' + uniqueId + '_' + item.id}"></label>
                </div>
            {/if}

            <div class="w-80">
                <textarea class="textarea"
                          value="{item.text}"
                          on:input="{e => updateElement(item, 'text', e.target.value)}"
                          rows="2"></textarea>
            </div>

            <div class="w-10">
                <div class="add-cursor has-text-centered" on:click="{() => deleteRow(item.id)}">
                    <Icon icon='{getContext("iconDelete")}' class="text-1dot5rem has-text-danger"/>
                </div>
            </div>
        </div>

    </Sortable>

</div>



<style>
    .btn-rounded {
        border-radius: 50%;
        padding: 0.25rem;
        width: 2.5rem;
    }

    .row-id {
        margin-top: 0.5rem;
        padding: 0.5rem 0.75rem;
        background-color: #EEE;
        border-radius: 50%;
    }
</style>

// imports/components/formBuilder/fieldTypes/vue-itemList.vue
<template>

    <fieldset class="box">

        <div class="text-1dot6rem add-cursor" v-on:click="addRow">
            <i class="has-text-primary" v-bind:class="rowAdd"></i>
        </div>

        <table class="table is-fullwidth">

            <Container v-on:drop="dropRow" tag="tbody" drag-handle-selector=".row-handle">
                <Draggable v-for="(row, idx) in rows" v-bind:key="row.id" tag="tr">

                    <td class="min-width">
                        <span class="add-cursor row-handle">
                            <i class="has-text-primary" v-bind:class="rowDrag"></i>
                        </span>
                    </td>

                    <td class="min-width">{{idx + 1}}</td>

                    <td class="min-width">
                        <div class="field" v-if="showCheck">
                            <input type="checkbox"
                                   class="is-checkradio is-primary has-background-color"
                                   title=""
                                   v-bind:id="'checkbox_' + uniqueId + '_' + idx"
                                   v-model="row.check"
                                   v-on:change.stop="updateRow(row)">

                            <label v-bind:for="'checkbox_' + uniqueId + '_' + idx"></label>
                        </div>
                    </td>

                    <td>
                        <textarea
                                class="textarea"
                                v-bind="attributes"
                                v-model="row.text"
                                v-on:keyup="updateRow(row)">

                        </textarea>
                    </td>

                    <td class="add-cursor min-width" v-on:click="deleteRow(row.id)">
                        <i class="has-text-danger" v-bind:class="rowRemove"></i>
                    </td>

                </Draggable>
            </Container>

        </table>

        <label class="has-float-label">{{cmpLabel}}</label>

    </fieldset>

</template>


<script>
    /**
     * @summary Vue Item List container for other input types.
     *
     * @memberof Components_Form
     * @function vue-itemList
     * @locus Client
     * @isTemplate true
     * @augments vue-formFields
     *
     * @requires {Container,Draggable}_from_"vue-smooth-dnd"
     *
     * @return nothing - emits: on-itemList with Object
     *
     */


    import {Container, Draggable} from "vue-smooth-dnd"

    export default {
        props: {
            id: String,
            label: String,
            label_switch: String,
            value: Array,
            parms: Object,
            attributes: Object,
            cmpLabel: String
        },

        data() {
            return {
                showCheck: !!( this.parms && this.parms.showCheck ),

                rows: [],
                rowAdd: kanen.icons.ROW_ADD,
                rowDrag: kanen.icons.DRAG,
                rowRemove: kanen.icons.DELETE,

                uniqueId: Math.random()
            }
        },

        components: {
            Container,
            Draggable,
        },

        watch: {
            value() {
                if( !_.isEmpty(this.value) ){
                    this.rows = this.value;
                }
            },
        },

        methods: {

            addRow() {
                let addItem = {
                    id: "row" + (this.rows.length + 1),
                    check: "",
                    text: "",
                };

                this.rows.push(addItem);
                this.$emit('on-itemlist', this.rows);
            },

            updateRow(row){
                this.rows = this.rows.map( (r) => r.id === row.id ? row : r);
                this.$emit('on-itemlist', this.rows);
            },

            deleteRow(rowid) {
                this.rows = this.rows.filter(row => row.id !== rowid);
                this.$emit('on-itemlist', this.rows);
            },

            dropRow(dropResult) {
                const {removedIndex, addedIndex, payload} = dropResult;

                if (removedIndex !== null || addedIndex !== null) {
                    const result = [...this.rows];
                    let itemToAdd = payload;

                    if (removedIndex !== null) {
                        itemToAdd = result.splice(removedIndex, 1)[0];
                    }

                    if (addedIndex !== null) {
                        result.splice(addedIndex, 0, itemToAdd);
                    }

                    this.rows = result;
                    this.$emit('on-itemlist', this.rows);
                }
            }
        }
    }
</script>


<style scoped>

    table {
        display: table;
        border-collapse: separate;
    }

    tr {
        display: table-row !important;
    }

    tr[style*="transform"] {
        border-collapse: separate !important;
    }

    .min-width {
        width: 1%;
        white-space: nowrap;
    }

</style>
