// imports/components/formBuilder/fields/textarea.svelte
<script>
    /**
     * Basic textarea box.
     *
     * @memberof Components:Form
     * @function textarea
     * @locus Client
     * @augments formWrapper
     *
     * @param {Object} field
     *
     * @emits 'on-inputentry' {value: value, error: errorVal} with string
     *
     */

    //* common props from parent
    export let field = {};

    //* support functions
    import {createEventDispatcher} from 'svelte';
    const dispatch = createEventDispatcher();

    //* local reactive variable
    let inValue = "";
    let checkValue = "";

    $: setValue(field.value);


    //* functions that mutate local variables
    function setValue(val){
        if(typeof val === 'object'){
            inValue =  JSON.stringify(val);
        }else{
            inValue = val;
        }
    }

    function checkInput(){
        let out = "";
        if(typeof field.value === 'object'){
            try{
                out =  JSON.parse(inValue);
            }catch{
                out = field.value;
            }

        }else{
            out = inValue;
        }

        dispatch('on-inputentry', {value: out, error: false} )
    }

</script>


<label id="{field.field}">
    <textarea class="textarea"
              bind:value={inValue}
              {...field.attributes}
              on:keyup="{checkInput}"></textarea>
</label>

// imports/components/formBuilder/fieldTypes/vue-textarea.vue
<template>

    <div>
        <textarea
                class="textarea"
                v-bind:class="id"
                v-bind="attributes"
                v-bind:placeholder="cmpLabel"
                v-model="taValue"
                v-on:keyup="hasKeyup(taValue)"
                v-on:input="hasInput(taValue)">
        </textarea>

        <label class="has-float-label">{{cmpLabel}}</label>
    </div>

</template>

<script>
    /**
     * @summary Vue basic textarea box.
     *
     * @memberof Components_Form
     * @function vue-textarea
     * @locus Client
     * @isTemplate true
     * @augments vue-formFields
     *
     * @return nothing - emits: onTextentry with string value
     *
     */

    export default {
        props: {
            id: String,
            value: [String, Object, Array],
            attributes: Object,
            cmpLabel: String
        },

        data() {
            return {
                taValue: ""
            }
        },

        watch: {

            value() {
                if(typeof this.value === 'object'){
                    this.taValue =  JSON.stringify(this.value);
                }else{
                    this.taValue = this.value;
                }
            }
        },
        methods: {
            hasKeyup(val){
                this.$emit('on-textentry', val);
            },

            hasInput(val){
                this.$emit('on-textentry', val);
            }
        }
    }
</script>
