// imports/components/formBuilder/fields/colourPicker.svelte
<script>
    /**
     * Field component for colour picker.
     *
     * @memberof Components:Form
     * @function colourPicker
     * @locus Client
     * @augments fieldWrapper
     *
     * @param {Object} field
     *
     * @emits: 'on-inputentry' {value: value, error: errorVal} with object
     *
     */

    //* common props from parent
    export let field = {};

    //* support functions
    import {createEventDispatcher} from 'svelte';
    const dispatch = createEventDispatcher();

    import {textColour} from '/imports/functions/textColour'

    //* local reactive variable
    let inValue = "";

    let swatches = buildSwatches();
    let selectedSwatch = "";
    let colour = "#000";

    $: setValue(field.value);


    //* functions that mutate local variables
    function setValue(val){
        inValue = val;
        selectedSwatch = val;
        colour = textColour(val);
    }

    function showValue(col) {
        selectedSwatch = col;
        inValue = col;
        colour = textColour(col);

        dispatch('on-inputentry', {value: inValue, error: false});
    }

    //* pure functions
    function buildSwatches() {

        return [
            ["rgb(255, 170, 170)", "rgb(255, 128, 128)", "rgb(255, 0, 0)", "rgb(200, 64, 64)", "rgb(128, 64, 64)"],
            ["rgb(170, 255, 170)", "rgb(128, 255, 128)", "rgb(0, 255, 0)", "rgb(64, 200, 64)", "rgb(64, 128, 64)"],
            ["rgb(170, 170, 255)", "rgb(128, 128, 255)", "rgb(0, 0, 255)", "rgb(64, 64, 200)", "rgb(64, 64, 128)"],

            ["rgb(255, 255, 170)", "rgb(255, 255, 128)", "rgb(255, 255, 0)", "rgb(255, 190, 0)", "rgb(255, 128, 0)"],
            ["rgb(255, 170, 255)", "rgb(255, 128, 255)", "rgb(255, 0, 255)", "rgb(200, 64, 200)", "rgb(128, 64, 128)"],
            ["rgb(170, 255, 255)", "rgb(128, 255, 255)", "rgb(0, 255, 255)", "rgb(64, 200, 200)", "rgb(64, 128, 128)"],

            ["rgb(240, 240, 240)", "rgb(170, 170, 170)", "rgb(128, 128, 128)", "rgb(64, 64, 64)", "rgb(0, 0, 0)"]
        ];
    }

</script>



<div class="colours">

    <label>
        <input class="input"
               {...field.attributes}
               bind:value={inValue}
               style="background-color: {selectedSwatch}; color: {colour}">
    </label>

    <div class="select-area mt-3">
        {#each swatches as row}
            <div class="d-flex">

                {#each row as col}
                    <div class=" add-cursor">

                        <div class="swatch"
                             style="background-color: {col}"
                             title="{col}"
                             on:click="{ () => showValue(col)}">
                        </div>

                    </div>
                {/each}

            </div>
        {/each}
    </div>

</div>



<style scoped>

    .swatch {
        height: 2rem;
        width: 2rem;
        border-radius: 50%;
        margin: 0.5rem;
    }

</style>

// imports/components/formBuilder/fieldTypes/vue-colourPicker.vue
<template>

    <div class="colours">

        <input class="input"
               v-bind="attributes"
               v-bind:placeholder="cmpLabel"
               v-bind:style="{backgroundColor: selectedSwatch, color: colour }"
               v-model="inValue">

        <label class="has-float-label">{{cmpLabel}}</label>

        <div class="select-area mt-3">
            <div class="d-flex" v-for="row in swatches">
                <div class=" add-cursor" v-for="col in row">

                    <div class="swatch"
                         v-bind:style="{backgroundColor: col }"
                         v-bind:title="col"
                         v-on:click="showValue(col)">
                    </div>

                </div>
            </div>
        </div>

    </div>

</template>

<script>
    /**
     * @summary Vue radio colour picker.
     *
     * @memberof Components_Form
     * @function vue-colourPicker
     * @locus Client
     * @isTemplate true
     * @augments vue-formFields
     *
     * @requires {textColour}_from_'/imports/client/functions/func-textColour'
     *
     * @return nothing - emits: on-colourentry with string rgb value
     *
     */

    import {textColour} from '/imports/client/functions/func-textColour'

    export default {
        props: {
            value: [String, Number],
            attributes: Object,
            cmpLabel: String,
        },

        data() {
            return {
                inValue: "",

                swatches: this.buildSwatches(),
                selectedSwatch: "",
                colour: "#000"
            }
        },

        watch: {

            value() {
                this.inValue = this.value;
                this.selectedSwatch = this.value;
                this.colour = textColour(this.value);
            }
        },

        methods: {

            buildSwatches() {

                return [
                    ["rgb(255, 170, 170)", "rgb(255, 128, 128)", "rgb(255, 0, 0)", "rgb(200, 64, 64)", "rgb(128, 64, 64)"],
                    ["rgb(170, 255, 170)", "rgb(128, 255, 128)", "rgb(0, 255, 0)", "rgb(64, 200, 64)", "rgb(64, 128, 64)"],
                    ["rgb(170, 170, 255)", "rgb(128, 128, 255)", "rgb(0, 0, 255)", "rgb(64, 64, 200)", "rgb(64, 64, 128)"],

                    ["rgb(255, 255, 170)", "rgb(255, 255, 128)", "rgb(255, 255, 0)", "rgb(255, 190, 0)", "rgb(255, 128, 0)"],
                    ["rgb(255, 170, 255)", "rgb(255, 128, 255)", "rgb(255, 0, 255)", "rgb(200, 64, 200)", "rgb(128, 64, 128)"],
                    ["rgb(170, 255, 255)", "rgb(128, 255, 255)", "rgb(0, 255, 255)", "rgb(64, 200, 200)", "rgb(64, 128, 128)"],

                    ["rgb(240, 240, 240)", "rgb(170, 170, 170)", "rgb(128, 128, 128)", "rgb(64, 64, 64)", "rgb(0, 0, 0)"]
                ];
            },

            showValue(col) {
                this.selectedSwatch = col;
                this.inValue = col;
                this.colour = textColour(col);

                this.$emit('on-colourentry', this.inValue);
            }
        }
    }
</script>

<style scoped>

    .swatch {
        height: 2rem;
        width: 2rem;
        border-radius: 50%;
        margin: 0.5rem;
    }

</style>
