// imports/components/formBuilder/fieldTypes/vue-radios.vue
<template>

    <div class="columns is-multiline">
        <div class="column radio-field" v-bind:class="classWidth" v-for="(rad, index) in source" v-bind:key="index">

            <input type="radio"
                   class="is-checkradio"
                   v-bind:id="radField + 'radio' + index"
                   v-bind:name="radField + 'radio'"
                   v-bind="attributes"
                   v-bind:value="rad._id"

                   v-model="radValue._id"
                   v-on:change.stop="emitRadio(radValue._id)">

            <label v-bind:for="radField + 'radio' + index"><span>{{ rad.name }}</span></label>

        </div>

        <label class="has-float-label">{{radLabel}}</label>
    </div>

</template>

<script>
    /**
     * @summary Vue basic radios.
     *
     * @memberof Components_Form
     * @function vue-radios
     * @locus Client
     * @isTemplate true
     * @augments vue-formFields
     *
     * @return nothing - emits: onRadios with string value
     *
     */

    export default {
        props: {
            value: Object,
            attributes: Object,
            radLabel: String,
            radField: String,
            parms: Object,

            source: {
                type: Array,
                default: () => {
                    return []
                },
                required: true
            }
        },

        data() {
            return {
                radValue: this.value
            }
        },

        computed: {
            classWidth() {
                let cols = this.parms && this.parms.cols ? this.parms.cols : 1;
                let width = Math.floor(12 / cols);
                return `is-${width}`;
            }
        },

        watch: {

            value() {
                this.radValue = this.value;
            }
        },
        methods: {
            emitRadio(selId){
                let item = _.findWhere(this.source, {_id: selId});
                this.$emit('on-radios', item);
            }
        }
    }
</script>

// imports/components/formBuilder/fields/radios.svelte
<script>
    /**
     * Basic radio group.
     *
     * @memberof Components:Form
     * @function radios
     * @locus Client
     * @augments formWrapper
     *
     * @param {Object} field
     * @param {Object} field.params - {col: number}
     *
     * @emits: 'on-inputentry' {value: value, error: false} with array of objects
     *
     */

    //* common props from parent
    export let field = {};

    //* support functions
    import {createEventDispatcher} from 'svelte';
    const dispatch = createEventDispatcher();
    import {getContext} from 'svelte'
    let formText = getContext("formText");
    let source = formText[field.field] && formText[field.field].selects ? formText[field.field].selects : [];

    //* local reactive variable
    let radValue = "";

    $: setValue(field.value);


    //* event handlers
    function emitRadio(selId){
        //** get text for _id values
        let item = source.find( (s) => s._id === selId )
        dispatch('on-inputentry', {value: item, error: false});
    }

    //* functions that mutate local variables
    function setValue(val){
        radValue = val._id;
    }

    function colWidth() {
        let cols = field.params && field.params.cols ? field.params.cols : 1;
        cols = cols === 7 ? null :  Math.round(12 / cols);
        return cols ? `is-${cols}` : "";
    }

</script>



<div class="box">
    <div class="columns is-multiline">
        {#each source as rad, index}
            <div class="column radio-field {colWidth()}">

                <input type="radio"
                       id="{rad.field + '_radio_' + index}"
                       class="is-checkradio"
                       title=""
                       {...field.attributes}
                       bind:group={radValue}
                       value={rad._id}
                       on:change|stopPropagation="{() => emitRadio(rad._id)}">

                <label for="{rad.field + '_radio_' + index}">{rad.name}</label>
            </div>
        {/each}
    </div>

</div>
