// imports/components/listCollections/vue-rowSize.vue
<template>

    <div class="field has-addons">
        <div class="control">
            <a class="button is-static">
                <i v-bind:class="iconRows"></i>
            </a>
        </div>

        <div class="control">
            <span class="select">

                <select v-model="initval"
                        v-on:change="changerow">

                    <option v-for="option in opts">{{option}}</option>
                </select>

            </span>
        </div>

    </div>

</template>


<script>
    /**
     * @summary Builds row selector and documents count.
     *
     * @memberof Components_List
     * @function vue-rowSize
     * @locus Client
     * @isTemplate true
     *
     * @param  {Object} config - decoration for row selector
     * @param  {String} label
     *
     * @returns {Object} - emits 'row-changed'
     *
     */

    export default {

        props: {
            config: Object,
        },

        data() {
            return {
                opts: [10, 15, 20, 30, 50, 100],      // sets the row length per page selection
                initval: 10,                             // set initial rows / page
                iconRows: kanen.icons.ROWS,               // icon value from global config
            }
        },

        methods: {
            changerow() {
                this.$emit('row-changed', {
                    row: this.initval
                });
            },
        }
    }
</script>

// imports/components/listCollections/rowSize.svelte
<script>
    /**
     * Builds row selector and documents count.
     *
     * @memberof Components:List
     * @function rowSize
     * @locus Client
     *
     * @param  {Object} config - decoration for row selector
     * @param  {String} label
     *
     * @returns {Object} - emits 'row-changed'
     *
     */

    //** support functions
    import {getContext} from 'svelte';
    import Icon from '/imports/components/elements/icon.svelte'
    import {createEventDispatcher} from 'svelte';
    const dispatch = createEventDispatcher();

    //* local reactive variables
    let opts = [10, 15, 20, 30, 50, 100];           // sets the row length per page selection
    let initval = 10;                               // set initial rows / page


    //* event handlers
    function changerow() {
        dispatch('row-changed', {
            row: initval
        });
    }

</script>


<div class="field has-addons">
    <div class="control">
        <a class="button is-static">
            <Icon icon='{getContext("iconRows")}' class="text-1dot5rem"/>
        </a>
    </div>

    <div class="control">
        <span class="select">
            <select bind:value="{initval}" on:change="{changerow}">
                {#each opts as option}
                    <option>{option}</option>
                {/each}
            </select>
        </span>
    </div>
</div>
